#!/usr/bin/env bash
#
# OmniRoute — one-time VPS preparation.
#
# Run this ONCE on a fresh VPS, as a sudo-capable non-root user, from a checkout
# of this repository:
#
#   sudo bash infra/bootstrap-vps.sh
#
# It creates /opt/omniroute, installs the stack files, and stops. It does NOT
# start anything: the first deployment is performed by deploy.sh, which is
# invoked by the GitHub Actions workflow (or by hand with an image digest).
#
set -Eeuo pipefail

APP_DIR="/opt/omniroute"
# UID/GID 1000 = the `bun` user baked into the OmniRoute image. The data
# bind-mount must be owned by it or the container cannot write storage.sqlite.
APP_UID=1000
APP_GID=1000

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SRC_DIR/.." && pwd)"

if [[ "$(id -u)" -ne 0 ]]; then
    echo "Run with sudo: sudo bash infra/bootstrap-vps.sh" >&2
    exit 1
fi

: "${SUDO_USER:?Run via sudo from a normal user account, not as a root login}"

echo "==> Creating $APP_DIR"
mkdir -p "$APP_DIR"/{caddy,state,data,backups}

echo "==> Installing stack files"
install -m 0644 "$SRC_DIR/compose.yml"        "$APP_DIR/compose.yml"
install -m 0644 "$SRC_DIR/caddy/Caddyfile"    "$APP_DIR/caddy/Caddyfile"
install -m 0750 "$SRC_DIR/deploy.sh"          "$APP_DIR/deploy.sh"
install -m 0644 "$SRC_DIR/image-retention.sh" "$APP_DIR/image-retention.sh"
install -m 0750 "$SRC_DIR/backup.sh"          "$APP_DIR/backup.sh"

# active.caddy is regenerated by deploy.sh on every deployment; only seed it if
# this is a genuinely fresh box, so a re-run of bootstrap never repoints traffic.
if [[ ! -f "$APP_DIR/caddy/active.caddy" ]]; then
    install -m 0644 "$SRC_DIR/caddy/active.caddy" "$APP_DIR/caddy/active.caddy"
fi

echo "==> Creating env files (only if absent — never clobber real secrets)"
for f in .app.env .tunnel.env; do
    if [[ ! -f "$APP_DIR/$f" ]]; then
        touch "$APP_DIR/$f"
        echo "    created empty $APP_DIR/$f — you must fill this in"
    else
        echo "    kept existing $APP_DIR/$f"
    fi
    chmod 600 "$APP_DIR/$f"
done

echo "==> Setting ownership"
chown -R "$SUDO_USER":"$SUDO_USER" "$APP_DIR"
# The data dir is written by the container's `bun` user, not by the SSH user.
chown -R "$APP_UID":"$APP_GID" "$APP_DIR/data"
chmod 750 "$APP_DIR/data"

echo "==> Firewall: SSH only — Cloudflare Tunnel is the only web ingress"
# The tunnel dials OUT to Cloudflare, so no inbound port other than 22 is ever
# needed. Debian/Ubuntu ship ufw; RHEL-family (Oracle Linux, Rocky, Alma) ship
# firewalld and no ufw at all.
if command -v ufw >/dev/null 2>&1; then
    ufw --force default deny incoming
    ufw --force default allow outgoing
    ufw allow 22/tcp
    ufw --force enable
    ufw status verbose
elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
    # Make the public zone explicit and idempotent: only SSH is publicly
    # reachable. Cloudflare Tunnel dials out, so web and application ports must
    # remain closed even if a previous installation opened them.
    firewall-cmd --permanent --zone=public --add-service=ssh >/dev/null
    firewall-cmd --permanent --zone=public --remove-service=http >/dev/null
    firewall-cmd --permanent --zone=public --remove-service=https >/dev/null
    for port in 8080/tcp 20128/tcp; do
        firewall-cmd --permanent --zone=public --remove-port="$port" >/dev/null
    done
    firewall-cmd --reload >/dev/null
    firewall-cmd --zone=public --list-all
else
    echo "    no ufw/firewalld — skipping. Ensure 80/443/8080/20128 stay closed."
fi

echo "==> Hardening SSH authentication"
install -d -o root -g root -m 0755 /etc/ssh/sshd_config.d
cat > /etc/ssh/sshd_config.d/99-hardening.conf <<'EOF'
PasswordAuthentication no
KbdInteractiveAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
MaxAuthTries 3
LoginGraceTime 30
EOF
chmod 0644 /etc/ssh/sshd_config.d/99-hardening.conf

# Never reload an invalid SSH configuration: losing the active SSH path would
# make a remote VPS unrecoverable without console access.
if ! sshd -t; then
    echo "ERROR: SSH hardening configuration failed validation" >&2
    exit 1
fi
systemctl reload sshd

# On RHEL-family hosts SELinux is Enforcing by default and would deny the
# container every write to the bind-mounted data dir. compose.yml carries `:z`
# on those mounts so Docker relabels them; warn if that assumption is broken.
if command -v getenforce >/dev/null 2>&1; then
    echo "==> SELinux: $(getenforce) (compose.yml uses :z relabelling — no action needed)"
fi

echo "==> Nightly SQLite backup at 03:17"
# /etc/cron.d needs a running cron daemon. Ubuntu ships `cron`; RHEL-family
# minimal images often do not ship `cronie` at all, which would silently mean
# no backups ever run.
# Read the listing into a variable first. Piping it straight into `grep -q`
# looks cleaner but is wrong under `set -o pipefail`: grep exits the moment it
# matches, systemctl takes SIGPIPE while still writing, and the pipeline returns
# 141 — so a HIT would be reported as a MISS.
cron_units="$(systemctl list-unit-files 2>/dev/null || true)"
if ! grep -qE '^(crond?|cronie)\.service' <<<"$cron_units"; then
    echo "    WARNING: no cron daemon found. Install it or backups will never run:"
    echo "      RHEL-family: sudo dnf install -y cronie && sudo systemctl enable --now crond"
    echo "      Debian/Ubuntu: sudo apt install -y cron && sudo systemctl enable --now cron"
fi
cat > /etc/cron.d/omniroute-backup <<CRON
# OmniRoute — online SQLite backup. In-app auto-backup is disabled
# (DISABLE_SQLITE_AUTO_BACKUP=true) so it cannot run twice during a
# blue/green overlap window; this cron is the single owner of backups.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
17 3 * * * $SUDO_USER $APP_DIR/backup.sh >> $APP_DIR/backups/backup.log 2>&1
CRON
chmod 644 /etc/cron.d/omniroute-backup

cat <<DONE

==============================================================
Bootstrap complete.

Remaining manual steps:

  1. Fill in $APP_DIR/.app.env
     (see infra/app.env.example in the repo)

  2. Fill in $APP_DIR/.tunnel.env with a single line:
       TUNNEL_TOKEN=eyJ...

  3. In the Cloudflare dashboard, point the tunnel's public hostname at:
       http://caddy:8080
     NOT http://localhost:8080 — cloudflared runs in its own container.

  4. Nothing to do for GHCR: the deploy workflow lends this box a short-lived
     GITHUB_TOKEN for the pull and logs out afterwards, so no long-lived
     registry credential is ever stored here.

  5. Add the SSH public key used by GitHub Actions to
       ~$SUDO_USER/.ssh/authorized_keys

  6. Push to the 'prod' branch (or run the workflow manually) to deploy.
     The first run bootstraps the blue slot and starts Caddy + cloudflared.

Nothing is running yet — that is expected.
==============================================================
DONE
