#!/usr/bin/env bash
#
# OmniRoute — one-time VPS preparation.
#
# Run this ONCE on a fresh VPS, as a sudo-capable non-root user, from a checkout
# of this repository:
#
#   sudo bash infra/bootstrap-vps.sh
#
# It creates /opt/omniroute, installs the stack files, and stops. It does NOT
# start anything: the first deployment is performed by deploy.sh, which is
# invoked by the GitHub Actions workflow (or by hand with an image digest).
#
set -Eeuo pipefail

APP_DIR="/opt/omniroute"
# UID/GID 1000 = the `node` user baked into the OmniRoute image. The data
# bind-mount must be owned by it or the container cannot write storage.sqlite.
APP_UID=1000
APP_GID=1000

SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SRC_DIR/.." && pwd)"

if [[ "$(id -u)" -ne 0 ]]; then
    echo "Run with sudo: sudo bash infra/bootstrap-vps.sh" >&2
    exit 1
fi

: "${SUDO_USER:?Run via sudo from a normal user account, not as a root login}"

echo "==> Creating $APP_DIR"
mkdir -p "$APP_DIR"/{caddy,state,data,backups,ops-bot/releases}

echo "==> Installing stack files"
install -m 0644 "$SRC_DIR/compose.yml"        "$APP_DIR/compose.yml"
install -m 0644 "$SRC_DIR/caddy/Caddyfile"    "$APP_DIR/caddy/Caddyfile"
install -m 0750 "$SRC_DIR/deploy.sh"          "$APP_DIR/deploy.sh"
install -m 0750 "$SRC_DIR/backup.sh"          "$APP_DIR/backup.sh"

# Install the fixed-operation privileged helper as a root-owned immutable path.
if [[ -f "$REPO_ROOT/scripts/ops/omniroute_opsctl.py" ]]; then
    install -o root -g root -m 0755 "$REPO_ROOT/scripts/ops/omniroute_opsctl.py" "/usr/local/sbin/omniroute-opsctl"
fi

# Install Telegram Ops Bot as one versioned release. Production deploys replace
# the `current` symlink only after every file is copied successfully.
if [[ -d "$REPO_ROOT/scripts/ops/telegram_ops_bot" ]]; then
    BOT_RELEASE="releases/bootstrap"
    mkdir -p "$APP_DIR/ops-bot/$BOT_RELEASE"
    cp -a "$REPO_ROOT/scripts/ops/telegram_ops_bot/." "$APP_DIR/ops-bot/$BOT_RELEASE/"
    chown -R root:root "$APP_DIR/ops-bot/$BOT_RELEASE"
    find "$APP_DIR/ops-bot/$BOT_RELEASE" -type d -exec chmod 0755 {} +
    find "$APP_DIR/ops-bot/$BOT_RELEASE" -type f -exec chmod 0644 {} +
    ln -sfn "$BOT_RELEASE" "$APP_DIR/ops-bot/current"
fi

# active.caddy is regenerated by deploy.sh on every deployment; only seed it if
# this is a genuinely fresh box, so a re-run of bootstrap never repoints traffic.
if [[ ! -f "$APP_DIR/caddy/active.caddy" ]]; then
    install -m 0644 "$SRC_DIR/caddy/active.caddy" "$APP_DIR/caddy/active.caddy"
fi

echo "==> Creating env files (only if absent — never clobber real secrets)"
for f in .app.env .tunnel.env; do
    if [[ ! -f "$APP_DIR/$f" ]]; then
        touch "$APP_DIR/$f"
        echo "    created empty $APP_DIR/$f — you must fill this in"
    else
        echo "    kept existing $APP_DIR/$f"
    fi
    chmod 600 "$APP_DIR/$f"
done

echo "==> Setting ownership"
chown -R "$SUDO_USER":"$SUDO_USER" "$APP_DIR"
# The data dir is written by the container's `node` user, not by the SSH user.
chown -R "$APP_UID":"$APP_GID" "$APP_DIR/data"
chmod 750 "$APP_DIR/data"

echo "==> Telegram Ops Bot: user, state, and permissions"
if ! id -u omniroute-ops >/dev/null 2>&1; then
    useradd --system --no-create-home --shell /usr/sbin/nologin omniroute-ops
    echo "    created system user omniroute-ops"
else
    echo "    kept existing system user omniroute-ops"
fi

mkdir -p /etc/omniroute /var/lib/omniroute-ops /var/log/omniroute-ops "$APP_DIR/ops-bot/releases"
# The blanket `chown -R "$SUDO_USER"` above walks the whole APP_DIR, so it undoes
# the root ownership the bot release was installed with. Re-assert it here: the
# service runs as omniroute-ops and must not be able to rewrite its own code.
# The production deploy installs releases the same way (prod-deploy.yml, step 2.3).
chown -R root:root "$APP_DIR/ops-bot"
chown -R omniroute-ops:omniroute-ops /var/lib/omniroute-ops /var/log/omniroute-ops
chmod 750 /var/lib/omniroute-ops /var/log/omniroute-ops
if [[ ! -f /etc/omniroute/ops-bot.env ]]; then
    install -o root -g omniroute-ops -m 0640 "$SRC_DIR/ops-bot.env.example" /etc/omniroute/ops-bot.env
fi

# Sudoers configuration for unprivileged bot
if [[ -f "$SRC_DIR/sudoers/omniroute-ops-bot" ]]; then
    echo "==> Installing sudoers policy for omniroute-ops"
    install -m 0440 "$SRC_DIR/sudoers/omniroute-ops-bot" "/etc/sudoers.d/omniroute-ops-bot"
    if command -v visudo >/dev/null 2>&1; then
        if ! visudo -cf "/etc/sudoers.d/omniroute-ops-bot"; then
            echo "ERROR: /etc/sudoers.d/omniroute-ops-bot failed visudo syntax check" >&2
            rm -f "/etc/sudoers.d/omniroute-ops-bot"
            exit 1
        fi
    fi
fi

# Systemd unit for operations bot
if [[ -f "$SRC_DIR/systemd/omniroute-ops-bot.service" ]]; then
    echo "==> Installing omniroute-ops-bot.service systemd unit"
    install -m 0644 "$SRC_DIR/systemd/omniroute-ops-bot.service" "/etc/systemd/system/omniroute-ops-bot.service"
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload
    fi
fi

# Check if bot is configured before enabling service
if [[ -f /etc/omniroute/ops-bot.env ]] && grep -qE '^OPS_TELEGRAM_BOT_TOKEN=[0-9]+:[A-Za-z0-9_-]+' /etc/omniroute/ops-bot.env; then
    if command -v systemctl >/dev/null 2>&1; then
        echo "==> Telegram Bot token detected — enabling omniroute-ops-bot.service"
        systemctl enable --now omniroute-ops-bot.service || true
    fi
else
    echo "==> Telegram Ops Bot service installed (disabled until OPS_TELEGRAM_BOT_TOKEN is set in /etc/omniroute/ops-bot.env)"
fi

echo "==> Firewall: SSH only — Cloudflare Tunnel is the only web ingress"
# The tunnel dials OUT to Cloudflare, so no inbound port other than 22 is ever
# needed. Debian/Ubuntu ship ufw; RHEL-family (Oracle Linux, Rocky, Alma) ship
# firewalld and no ufw at all.
if command -v ufw >/dev/null 2>&1; then
    ufw --force default deny incoming
    ufw --force default allow outgoing
    ufw allow 22/tcp
    # Webhook mode only: Caddy runs in a container and reaches the host-side ops
    # bot over the docker bridge, so the listener cannot bind loopback. Scope the
    # opening to RFC1918 space docker allocates its bridges from — the port stays
    # closed to the internet, which default-deny already handles for everything else.
    ufw allow from 172.16.0.0/12 to any port "${OPS_WEBHOOK_PORT:-20129}" proto tcp
    ufw --force enable
    ufw status verbose
elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
    # Only ensure SSH survives; deliberately open nothing else. firewalld's
    # default zone already drops unsolicited inbound traffic.
    firewall-cmd --permanent --add-service=ssh >/dev/null
    # Same reason as the ufw rule above: in webhook mode the containerised Caddy
    # reaches the host-side ops bot over the docker bridge, and firewalld's
    # default zone would otherwise drop it. Scoped to the RFC1918 range docker
    # allocates bridges from, so this opens nothing to the internet.
    firewall-cmd --permanent --add-rich-rule \
        "rule family=\"ipv4\" source address=\"172.16.0.0/12\" port port=\"${OPS_WEBHOOK_PORT:-20129}\" protocol=\"tcp\" accept" >/dev/null
    firewall-cmd --reload >/dev/null
    firewall-cmd --list-all
else
    echo "    no ufw/firewalld — skipping. Ensure 80/443/8080/20128 stay closed."
fi

# On RHEL-family hosts SELinux is Enforcing by default and would deny the
# container every write to the bind-mounted data dir. compose.yml carries `:z`
# on those mounts so Docker relabels them; warn if that assumption is broken.
if command -v getenforce >/dev/null 2>&1; then
    echo "==> SELinux: $(getenforce) (compose.yml uses :z relabelling — no action needed)"
fi

echo "==> Nightly SQLite backup at 03:17"
# /etc/cron.d needs a running cron daemon. Ubuntu ships `cron`; RHEL-family
# minimal images often do not ship `cronie` at all, which would silently mean
# no backups ever run.
# Read the listing into a variable first. Piping it straight into `grep -q`
# looks cleaner but is wrong under `set -o pipefail`: grep exits the moment it
# matches, systemctl takes SIGPIPE while still writing, and the pipeline returns
# 141 — so a HIT would be reported as a MISS.
cron_units="$(systemctl list-unit-files 2>/dev/null || true)"
if ! grep -qE '^(crond?|cronie)\.service' <<<"$cron_units"; then
    echo "    WARNING: no cron daemon found. Install it or backups will never run:"
    echo "      RHEL-family: sudo dnf install -y cronie && sudo systemctl enable --now crond"
    echo "      Debian/Ubuntu: sudo apt install -y cron && sudo systemctl enable --now cron"
fi
cat > /etc/cron.d/omniroute-backup <<CRON
# OmniRoute — online SQLite backup. In-app auto-backup is disabled
# (DISABLE_SQLITE_AUTO_BACKUP=true) so it cannot run twice during a
# blue/green overlap window; this cron is the single owner of backups.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
17 3 * * * $SUDO_USER $APP_DIR/backup.sh >> $APP_DIR/backups/backup.log 2>&1
CRON
chmod 644 /etc/cron.d/omniroute-backup

cat <<DONE

==============================================================
Bootstrap complete.

Remaining manual steps:

  1. Fill in $APP_DIR/.app.env
     (see infra/app.env.example in the repo)

  2. Fill in $APP_DIR/.tunnel.env with a single line:
       TUNNEL_TOKEN=eyJ...

  3. Fill in /etc/omniroute/ops-bot.env to configure the Telegram Ops Bot:
       (see infra/ops-bot.env.example and docs/ops/TELEGRAM_OPS_BOT.md)
     Then enable and start the service:
       sudo systemctl enable --now omniroute-ops-bot.service

  4. In the Cloudflare dashboard, point the tunnel's public hostname at:
       http://caddy:8080
     NOT http://localhost:8080 — cloudflared runs in its own container.

  5. Nothing to do for GHCR: the deploy workflow lends this box a short-lived
     GITHUB_TOKEN for the pull and logs out afterwards, so no long-lived
     registry credential is ever stored here.

  6. Add the SSH public key used by GitHub Actions to
       ~$SUDO_USER/.ssh/authorized_keys

  7. Push to the 'prod' branch (or run the workflow manually) to deploy.
     The first run bootstraps the blue slot and starts Caddy + cloudflared.

Nothing is running yet — that is expected.
==============================================================
DONE
